title: Hackerspace Monterrey
url: http://hsmty.org
exclude: [README.md, LICENSE, Rakefile.rb, Gemfile, Gemfile.lock]
permalink: /blog/:year/:month/:title
timezone: America/Monterrey
encoding: UTF-8
markdown: kramdown
highlighter: rouge
future: false
paginate: 5
paginate_path: blog/:num

defaults:
    -
        scope:
            path: ""
            type: "post"
        values:
            layout: "post"
